## H2 DB
spring.datasource.url=jdbc:h2:tcp://localhost/~/db/oauth
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

#hibernate ??
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.hibernate.ddl-auto=create-drop
#logging.level.org.hibernate=trace

# for using korean URL resource path
server.tomcat.uri-encoding=UTF-8

# security
spring.security.oauth2.client.registration.google.client-id=
logging.level.org.springframework.security=DEBUG